"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type EntryType = "REVENUE" | "EXPENSE";
const categories = { REVENUE: ["Venda avulsa", "Evento", "Produto", "Serviço", "Outro"], EXPENSE: ["Operação", "Marketing", "Equipe", "Equipamento", "Impostos", "Outro"] };

export function FinancialEntryManager({ month }: { month: string }) { return <FinancialEntryForm month={month} initialType="EXPENSE" />; }

export function FinancialMobileActions({ month }: { month: string }) {
  const [type, setType] = useState<EntryType | null>(null);
  return <><div className="financial-mobile-actions"><button type="button" className="expense" onClick={() => setType("EXPENSE")}><b>−</b> Saída</button><button type="button" onClick={() => setType("REVENUE")}><b>+</b> Entrada</button></div>{type ? <div className="financial-entry-modal" role="dialog" aria-modal="true" aria-label={type === "EXPENSE" ? "Registrar saída" : "Registrar entrada"}><button className="financial-entry-backdrop" type="button" aria-label="Fechar" onClick={() => setType(null)} /><section><div className="financial-entry-modal-heading"><div><p className="eyebrow">{type === "EXPENSE" ? "Nova saída" : "Nova entrada"}</p><h2>{type === "EXPENSE" ? "Registrar saída" : "Registrar entrada"}</h2></div><button type="button" onClick={() => setType(null)} aria-label="Fechar">×</button></div><FinancialEntryForm key={type} month={month} initialType={type} onSaved={() => setType(null)} /></section></div> : null}</>;
}

function FinancialEntryForm({ month, initialType, onSaved }: { month: string; initialType: EntryType; onSaved?: () => void }) {
  const router = useRouter(); const [type, setType] = useState<EntryType>(initialType); const [title, setTitle] = useState(""); const [category, setCategory] = useState(categories[initialType][0]); const [description, setDescription] = useState(""); const [amount, setAmount] = useState(""); const [occurredAt, setOccurredAt] = useState(`${month}-01`); const [isFixed, setIsFixed] = useState(false); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  function changeType(next: EntryType) { setType(next); setCategory(categories[next][0]); }
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); const response = await fetch("/api/admin/financial-entries", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type, title, category, description, amount, occurredAt, isFixed }) }); const data = await response.json().catch(() => null); setSaving(false); if (!response.ok) return setMessage(data?.error ?? "Não foi possível salvar."); setTitle(""); setDescription(""); setAmount(""); setMessage("Lançamento registrado."); router.refresh(); onSaved?.(); }
  return <form className="financial-entry-form" onSubmit={submit}><div className="financial-entry-type"><button type="button" className={type === "EXPENSE" ? "active expense" : ""} onClick={() => changeType("EXPENSE")}>Saída</button><button type="button" className={type === "REVENUE" ? "active" : ""} onClick={() => changeType("REVENUE")}>Entrada</button></div><div className="field"><label htmlFor="financial-title">Título</label><input id="financial-title" value={title} onChange={(event) => setTitle(event.target.value)} placeholder={type === "REVENUE" ? "Ex.: Venda de camiseta" : "Ex.: Aluguel da pista"} required /></div><div className="financial-entry-fields"><div className="field"><label htmlFor="financial-category">Categoria</label><select id="financial-category" value={category} onChange={(event) => setCategory(event.target.value)}>{categories[type].map((item) => <option key={item}>{item}</option>)}</select></div><div className="field"><label htmlFor="financial-amount">Valor (R$)</label><input id="financial-amount" inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0,00" required /></div></div><div className="financial-entry-fields financial-entry-schedule"><div className="field"><label htmlFor="financial-date">Data</label><input id="financial-date" type="date" value={occurredAt} onChange={(event) => setOccurredAt(event.target.value)} required /></div><label className="financial-fixed"><input type="checkbox" checked={isFixed} onChange={(event) => setIsFixed(event.target.checked)} /><span><strong>Fixo</strong><small>Repete todo mês</small></span></label></div><div className="field"><label htmlFor="financial-description">Descrição <em>opcional</em></label><textarea id="financial-description" rows={3} value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Adicione detalhes para facilitar a conferência." /></div>{message ? <p className={message === "Lançamento registrado." ? "success-message" : "error-message"}>{message}</p> : null}<button className="button button-dark" type="submit" disabled={saving}>{saving ? "Salvando…" : type === "REVENUE" ? "Registrar entrada" : "Registrar saída"}</button></form>;
}
