-- A funcionalidade de múltiplos produtos foi descontinuada antes de chegar à produção.
-- Mantemos este arquivo vazio para que bancos que registraram a tentativa anterior
-- possam concluir o histórico de migrations sem alterar a estrutura existente.
